# Generated by Django 4.2 on 2023-04-22 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Manager", "0002_remove_tasks_grt"),
    ]

    operations = [
        migrations.RemoveField(model_name="tasks", name="grt",),
    ]
